service: simple-project

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 1024
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-2

functions: 
  generate-dog-name:
    handler: src/handlers/generate-dog-name/generate-dog-name.handler
    events: 
      - http: 
          path: generate/{breed}/name
          method: get
          cors: true
  
  slack-notifications: 
    handler: src/handlers/slack-notification/slack-notification.handler
    environment: 
      SLACK_WEBHOOK_URL: ${ssm:/error-slack-webhook-url~true} #Make sure to create the secret first. Note true means you want to decrypt value
    events: 
      - sns: 
          arn: 
            Ref: NotifySlackSns
          topicName: ${self:service}-${self:provider.stage}-NotifySlackSns

resources: 
  Resources:
    NotifySlackSns:
      Type: AWS::SNS::Topic
      Properties: 
        TopicName: ${self:service}-${self:provider.stage}-NotifySlackSns

    CheckValidStringErrorAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: ${self:service}-${self:provider.stage}-GenerateDogName
        AlarmDescription: Lambda alarm
        Namespace: AWS/Lambda
        MetricName: Errors
        Dimensions:
          - Name: FunctionName
            Value: 
              Ref: GenerateDashdogDashnameLambdaFunction
        Statistic: Sum
        ComparisonOperator: GreaterThanThreshold
        Threshold: 0
        Period: 60
        EvaluationPeriods: 1
        AlarmActions:
          - Ref: NotifySlackSns

    # CheckValidStringErrorFilter: 
    #   Type: AWS::Logs::MetricFilter
    #   Properties:
    #     LogGroupName:
    #       Ref: 'CheckDashvalidDashstringLogGroup'
    #     FilterPattern: '{$.level = "error"}'
    #     MetricTransformations:
    #       -
    #         MetricValue: '1'
    #         MetricNamespace: 'LogMetrics'
    #         MetricName: '${self:service}-${self:provider.stage}-CheckValidStringError'

    # CheckValidStringErrorAlarm:
    #   Type: AWS::CloudWatch::Alarm
    #   Properties:
    #     AlarmName: ${self:service}-${self:provider.stage}-CheckValidStringError
    #     AlarmDescription: Lambda alarm
    #     Namespace: LogMetrics
    #     MetricName: ${self:service}-${self:provider.stage}-CheckValidStringError
    #     Statistic: Sum
    #     ComparisonOperator: GreaterThanThreshold
    #     Threshold: 0
    #     Period: 60
    #     EvaluationPeriods: 1
    #     AlarmActions:
    #       - Ref: NotifySlackSns